name: Emu pull request

on:
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**/*.md'
      - 'dev.notes/**'
      - 'post_build/**'
      - 'z_original_repo_files/**'
      - 'sdk/*.txt'
      - 'LICENSE'
      # tools
      - 'tools/generate_emu_config/**'
      - 'tools/migrate_gse/**'
      - 'tools/steamclient_loader/linux/**' # these are just scripts, not built

permissions:
  contents: write

jobs:
  emu-win-all:
    name: Emu win all
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-all-win.yml

  emu-linux-all:
    name: Emu linux all
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/emu-build-all-linux.yml
