name: Emu pull request

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - '!**/*.md'
      - 'tools/generate_emu_config/**'

permissions:
  contents: write

jobs:
  script-win:
    name: Gen emu config win
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/gen_emu_config-build-win.yml

  script-linux:
    name: Gen emu config linux
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/gen_emu_config-build-linux.yml
